py.install_sources(
  '7_Days_to_Die.png',
  'balatro.png',
  'baldurs_gate_3.png',
  'cyberpunk_2077.png',
  'daggerfall_unity.png',
  'darktide.png',
  'devil_may_cry_5.png',
  'dragon_age_origins.png',
  'dragons_dogma_2.png',
  'dysonsphereprogram.png',
  'elden_ring.png',
  'enderal.png',
  'enderalse.png',
  'Fallout3GOTY.png',
  'Fallout3.png',
  'Fallout4.png',
  'Fallout4VR.png',
  'Fallout76.png',
  'FalloutNC.png',
  'FalloutNV.png',
  'Fallout_London.png',
  'Hades.png',
  'Hades_II.png',
  'hogwarts_legacy.png',
  'Hollow_Knight_Silksong.png',
  'inscryption.png',
  'jagged_alliance_3.png',
  'kingdom_come_deliverance_2.png',
  'kingdom_come_deliverance.png',
  'Lethal_Company.png',
  'marvel_rivals.png',
  'mewgenics.png',
  'nightreign.png',
  'monster_hunter_rise.png',
  'monster_hunter_wilds.png',
  'morrowind_openmw.png',
  'morrowind.png',
  'Mount___Blade_II__Bannerlord.png',
  'No_Man_s_Sky.png',
  'Oblivion.png',
  'oblivion_remastered.png',
  'peak.png',
  'pragmata.png',
  'Project_Zomboid.png',
  'red_dead_redemption_2.png',
  'repo.png',
  'resident_evil_2.png',
  'resident_evil_3.png',
  'resident_evil_4.png',
  'resident_evil_7.png',
  'resident_evil_requiem.png',
  'resident_evil_village.png',
  'riskofrain2.png',
  'skyrim.png',
  'skyrim_se.png',
  'skyrimvr.png',
  'Slay_The_Spire_2.png',
  'Stardew_Valley.png',
  'Starfield.png',
  'street_fighter_6.png',
  'Subnautica_Below_Zero.png',
  'subnautica.png',
  'Supermarket_Simulator.png',
  'TCG_Card_Shop_Simulator.png',
  'the_sims_4.png',
  'Valheim.png',
  'Voices_Of_The_Void.png',
  'witcher_3.png',
  subdir: 'icons' / 'games',
)
